made all changes except PR template
zowe/perf-timing pull request #59
Opened 2023-05-04 19:20 UTC by ATorrise

2023-05-08 17:49 UTC, zFernand0 requested changes

2023-05-08 17:49 UTC, zFernand0 commented on .github/ISSUE_TEMPLATE/bug_report copy.md
should this file be renamed to just `bug_report.md`?

2023-05-08 17:49 UTC, zFernand0 commented on .github/ISSUE_TEMPLATE/config.yml
> +    url: https://github.com/zowe/perf-timing/discussions
I know this repo is likely to go away, but curious if we should point people directly to the Q&A section

2023-05-08 17:49 UTC, zFernand0 commented on .github/workflows/changelog.yml
Can we update `awharn/check_changelog_action@v0.0.2` to `v1`?

2023-05-09 03:57 UTC, t1m0thyj approved these changes

2023-05-09 13:17 UTC, merged